server:
  port: 8888
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql:///ss_test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
